[build]
  command = "npm run build"
  publish = ".next"

# Environment variables (Note: This is NOT recommended for sensitive data)
# Instead, use the Netlify Dashboard to set these securely
[build.environment]
  # NEXT_PUBLIC_SUPABASE_URL = "https://mwzalxctdbpnourkyjcp.supabase.co"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_key_here"

[[plugins]]
  package = "@netlify/plugin-nextjs"